;(setq LEXMEM '(((TEENAGER) MODIF AGE (RANGE FROM (13) TO (19) UNIT (YEAR)) ((DM-MODIF HUMAN AFTER)))))
(ADD-LEX '(HOT) '(WEATHER) NIL)
(ADD-LEX '(HOT DOG) '(FOOD) NIL)
(ADD-LEX '(TEENAGER) '(HUMAN GENDER(MALE)) NIL)
